---
- hosts: localhost
  gather_facts: no
  tasks:
    - amazon.aws.ec2:
        region: '{{ region }}'
        key_name: '{{ keypair }}'
        instance_type: 't2.micro'
        image: '{{ ubuntu }}'
        group_id: '{{ bastion_sg_id }}'
        vpc_subnet_id: '{{ webapp_public_subnet_id }}'
        assign_public_ip: no

     
